### PR TITLE
Returning correct units gyro

### PR DESCRIPTION
**Pull request by jposada202020**
Correcting Gyro returning Units from DPS to rad/s

### CODE REVIEW

**Comment by ladyada** [comment]
kk did you try this on hardware?

**Comment by jposada202020** [comment]
Not this one, I test the L3GD20 and the MPU6050. I verify that the lambda function was working with this :)
```python
def gyro():
    """The gyroscope X, Y, Z axis values as a 3-tuple of
    degrees/second values.
    """
    raw = (1, 2, 3)
    return map(lambda x: math.radians(x * gyro_dps_digit), raw)

 # * 0.01745277777777778
a, b, c = gyro()
print(a,b,c)

# print(5*3.1415/180)
# print(10*3.1415/180)
# print(15*3.1415/180)
#
# print(math.radians(5))
# print(math.radians(10))
# print(math.radians(15))

# 0.08726646259971647
# 0.17453292519943295
# 0.2617993877991494
```

**Comment by ladyada** [comment]
kk - what was the circuitpy board?

**Comment by jposada202020** [comment]
tested in 
```python
Adafruit CircuitPython 6.2.0 on 2021-04-05; Adafruit Feather RP2040 with rp2040
```

**Comment by ladyada** [comment]
oki just makin sure its not just CPython :)

**Comment by jposada202020** [comment]
:), no I was not sure that radians existed in CP so that I did all the granular tests... but one of the good gyro library uses radians, so it was not my idea I just copy from there.

**Pull request merged**
